name: Playwright Tests
on:
  push:
    branches: 
      - main,
      - feature/**
  pull_request:
    branches: 
      - main,
      - feature/**
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Website URL to test'
        required: false
        default: 'https://www.saucedemo.com'

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ github.event.inputs.base_url || 'https://www.saucedemo.com' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Show test environment
      run: echo "BASE_URL=$BASE_URL"
    - name: Run Playwright tests
      run: npm test
    - name: Upload Playwright artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-artifacts-${{ github.run_id }}
        path: |
          playwright/test-results/
          playwright-report/
        retention-days: 30
